let currentBackgroundStyle = 'curves';
let currentLogoPosition = 'top-right';
let currentCyberOverlay = 'none';
let currentLanguage = 'en';
let currentLogoShadowType = 'glow';
let customPresets = {};
let layers = [];
let selectedLayerId = null;

// Returns a fresh default array of standard poster layers
function getLayersDefaultTemplate() {
    return [
        {
            id: 'layer_logo_1',
            name: 'Brand Logo 1',
            type: 'image',
            position: { left: 32, top: 32 },
            size: { width: 95, height: 95 },
            visible: true,
            zIndex: 100,
            src: 'Biu_tzadik_nobackground.png',
            shape: 'rect',
            crop: { x: 0, y: 0, zoom: 100 },
            hasBg: false,
            bgColorHex: '#ffffff',
            hasShadow: false,
            shadowColorHex: '#000000',
            shadowType: 'glow'
        },
        {
            id: 'layer_callout_left',
            name: 'Left Callout',
            type: 'text',
            position: { left: 32, top: 32 },
            size: { width: 230, height: 60 },
            visible: true,
            zIndex: 90,
            text: 'Or just learn how hackers think and operate',
            fontSize: 15,
            fontFamily: 'font-secular',
            colorMode: 'theme-light',
            alignment: 'auto'
        },
        {
            id: 'layer_callout_right',
            name: 'Right Callout',
            type: 'text',
            position: { left: 323, top: 32 },
            size: { width: 240, height: 60 },
            visible: true,
            zIndex: 80,
            text: 'Come acquire knowledge that could be relevant to your career!',
            fontSize: 15,
            fontFamily: 'font-secular',
            colorMode: 'theme-dark',
            alignment: 'auto'
        },
        {
            id: 'layer_title_1',
            name: 'Title Line 1',
            type: 'text',
            position: { left: 32, top: 250 },
            size: { width: 531, height: 50 },
            visible: true,
            zIndex: 70,
            text: 'Introduction to Cyber:',
            fontSize: 36,
            fontFamily: 'font-secular',
            colorMode: 'theme-dark',
            alignment: 'auto'
        },
        {
            id: 'layer_title_2',
            name: 'Title Line 2',
            type: 'text',
            position: { left: 32, top: 300 },
            size: { width: 531, height: 50 },
            visible: true,
            zIndex: 60,
            text: 'From Viruses to Careers',
            fontSize: 34,
            fontFamily: 'font-secular',
            colorMode: 'theme-dark',
            alignment: 'auto'
        },
        {
            id: 'layer_date',
            name: 'Event Date',
            type: 'text',
            position: { left: 32, top: 380 },
            size: { width: 531, height: 30 },
            visible: true,
            zIndex: 50,
            text: 'Thursday, 25.12.2025',
            fontSize: 19,
            fontFamily: 'font-varela',
            colorMode: 'theme-dark',
            alignment: 'auto'
        },
        {
            id: 'layer_time',
            name: 'Event Time',
            type: 'text',
            position: { left: 32, top: 420 },
            size: { width: 531, height: 30 },
            visible: true,
            zIndex: 40,
            text: '14:00-15:00',
            fontSize: 19,
            fontFamily: 'font-varela',
            colorMode: 'theme-dark',
            alignment: 'auto'
        },
        {
            id: 'layer_location',
            name: 'Event Location',
            type: 'text',
            position: { left: 32, top: 460 },
            size: { width: 531, height: 30 },
            visible: true,
            zIndex: 30,
            text: 'Building 503 (CS) Room 226',
            fontSize: 17,
            fontFamily: 'font-varela',
            colorMode: 'theme-dark',
            alignment: 'auto'
        },
        {
            id: 'layer_speaker_name',
            name: 'Speaker Name',
            type: 'text',
            position: { left: 32, top: 660 },
            size: { width: 340, height: 35 },
            visible: true,
            zIndex: 20,
            text: 'Speaker Name',
            fontSize: 22,
            fontFamily: 'font-secular',
            colorMode: 'theme-dark',
            alignment: 'auto'
        },
        {
            id: 'layer_speaker_role',
            name: 'Speaker Role',
            type: 'text',
            position: { left: 32, top: 700 },
            size: { width: 340, height: 40 },
            visible: true,
            zIndex: 10,
            text: "Speaker's Role / Company",
            fontSize: 13,
            fontFamily: 'font-varela',
            colorMode: 'theme-dark',
            alignment: 'auto'
        },
        {
            id: 'layer_speaker_portrait',
            name: 'Speaker Portrait',
            type: 'image',
            position: { left: 413, top: 640 },
            size: { width: 150, height: 150 },
            visible: true,
            zIndex: 5,
            src: 'https://placehold.co/300x300/004124/71CCE7?text=Speaker',
            shape: 'circle',
            crop: { x: -154, y: -386, zoom: 440 },
            borderColor: '#004124',
            borderWidth: 4
        }
    ];
}

// Built-in presets stored directly in script to bypass offline CORS file blocks
const BUILT_IN_PRESETS = {
    "tzadik-he": {
        calloutLeft: 'או סתם ללמוד איך האקרים חושבים ופועלים',
        calloutRight: 'בואו לרכוש ידע שיכול להיות רלוונטי לקריירה שלכם!',
        title1: 'מבוא לסייבר:',
        title2: 'וירוסים ועד קריירות',
        date: 'יום חמישי, 25.12.2025',
        time: '14:00-15:00',
        location: 'בניין 503 (מדע״ח) חדר 226',
        speakerName: 'שם המרצה',
        speakerRole: 'תפקיד המרצה / חברה',
        theme: 'tzadik',
        bgStyle: 'curves',
        cyberOverlay: 'none',
        logoVisible: true,
        logoBg: false,
        logoPosition: 'top-right',
        logoSize: 95,
        avatarZoom: 440,
        avatarX: -154,
        avatarY: -386,
        fzTitle: 36,
        fzCallouts: 15,
        fzDetails: 19,
        fzSpeaker: 22,
        verticalShift: 0,
        primaryColor: '#004124',
        secondaryColor: '#71CCE7',
        textDarkColor: '#0f2219',
        textLightColor: '#000000',
        layoutDirection: 'rtl',
        uiLanguage: 'he',
        speakerImgSrc: 'https://placehold.co/300x300/004124/71CCE7?text=Speaker',
        logoImgSrc: 'Biu_tzadik_nobackground.png'
    },
    "tzadik-en": {
        calloutLeft: 'Or just learn how hackers think and operate',
        calloutRight: 'Come acquire knowledge that could be relevant to your career!',
        title1: 'Introduction to Cyber:',
        title2: 'From Viruses to Careers',
        date: 'Thursday, 25.12.2025',
        time: '14:00-15:00',
        location: 'Building 503 (CS) Room 226',
        speakerName: 'Speaker Name',
        speakerRole: "Speaker's Role / Company",
        theme: 'tzadik',
        bgStyle: 'curves',
        cyberOverlay: 'none',
        logoVisible: true,
        logoBg: false,
        logoPosition: 'top-left',
        logoSize: 95,
        avatarZoom: 440,
        avatarX: -154,
        avatarY: -386,
        fzTitle: 36,
        fzCallouts: 15,
        fzDetails: 19,
        fzSpeaker: 22,
        verticalShift: 0,
        primaryColor: '#004124',
        secondaryColor: '#71CCE7',
        textDarkColor: '#0f2219',
        textLightColor: '#000000',
        layoutDirection: 'ltr',
        uiLanguage: 'en',
        speakerImgSrc: 'https://placehold.co/300x300/004124/71CCE7?text=Speaker',
        logoImgSrc: 'Biu_tzadik_nobackground.png'
    },
    "original-he": {
        calloutLeft: 'או סתם ללמוד איך האקרים חושבים ופועלים',
        calloutRight: 'בואו לרכוש ידע שיכול להיות רלוונטי לקריירה שלכם!',
        title1: 'מבוא לסייבר:',
        title2: 'וירוסים ועד קריירות',
        date: 'יום חמישי, 25.12.2025',
        time: '14:00-15:00',
        location: 'בניין 503 (מדע״ח) חדר 226',
        speakerName: 'שם המרצה',
        speakerRole: 'תפקיד המרצה / חברה',
        theme: 'original',
        bgStyle: 'curves',
        cyberOverlay: 'none',
        logoVisible: true,
        logoBg: false,
        logoPosition: 'top-right',
        logoSize: 95,
        avatarZoom: 440,
        avatarX: -154,
        avatarY: -386,
        fzTitle: 36,
        fzCallouts: 15,
        fzDetails: 19,
        fzSpeaker: 22,
        verticalShift: 0,
        primaryColor: '#091e36',
        secondaryColor: '#00b0ff',
        textDarkColor: '#081c33',
        textLightColor: '#000000',
        layoutDirection: 'rtl',
        uiLanguage: 'he',
        speakerImgSrc: 'https://placehold.co/300x300/091e36/00b0ff?text=Speaker',
        logoImgSrc: 'Biu_tzadik_nobackground.png'
    },
    "original-en": {
        calloutLeft: 'Or just learn how hackers think and operate',
        calloutRight: 'Come acquire knowledge that could be relevant to your career!',
        title1: 'Introduction to Cyber:',
        title2: 'From Viruses to Careers',
        date: 'Thursday, 25.12.2025',
        time: '14:00-15:00',
        location: 'Building 503 (CS) Room 226',
        speakerName: 'Speaker Name',
        speakerRole: "Speaker's Role / Company",
        theme: 'original',
        bgStyle: 'curves',
        cyberOverlay: 'none',
        logoVisible: true,
        logoBg: false,
        logoPosition: 'top-left',
        logoSize: 95,
        avatarZoom: 440,
        avatarX: -154,
        avatarY: -386,
        fzTitle: 36,
        fzCallouts: 15,
        fzDetails: 19,
        fzSpeaker: 22,
        verticalShift: 0,
        primaryColor: '#091e36',
        secondaryColor: '#00b0ff',
        textDarkColor: '#081c33',
        textLightColor: '#000000',
        layoutDirection: 'ltr',
        uiLanguage: 'en',
        speakerImgSrc: 'https://placehold.co/300x300/091e36/00b0ff?text=Speaker',
        logoImgSrc: 'Biu_tzadik_nobackground.png'
    },
    "f5-he": {
        calloutLeft: "אבטחה, שליחה ואופטימיזציה של כל אפליקציה, בכל מקום",
        calloutRight: "בואו ללמוד על אבטחת אפליקציות ופתרונות F5!",
        title1: "הרצאת סייבר:",
        title2: "אבטחת אפליקציות ופתרונות F5",
        date: "יום חמישי, 12.06.2026",
        time: "14:00-15:00",
        location: "בניין 503 (מדע״ח) חדר 226",
        speakerName: "שם המרצה",
        speakerRole: "מהנדס/ת אבטחה / F5",
        theme: "f5",
        bgStyle: "curves",
        cyberOverlay: "none",
        logoVisible: true,
        logoBg: false,
        logoPosition: "top-right",
        logoSize: 95,
        avatarZoom: 440,
        avatarX: -154,
        avatarY: -386,
        fzTitle: 36,
        fzCallouts: 15,
        fzDetails: 19,
        fzSpeaker: 22,
        verticalShift: 0,
        primaryColor: "#1D252D",
        secondaryColor: "#E4002B",
        textDarkColor: "#1D252D",
        textLightColor: "#ffffff",
        layoutDirection: "rtl",
        uiLanguage: "he",
        speakerImgSrc: "https://placehold.co/300x300/1D252D/E4002B?text=Speaker",
        logoImgSrc: "Biu_tzadik_nobackground.png"
    },
    "f5-en": {
        calloutLeft: "Secure, deliver, and optimize any app, anywhere",
        calloutRight: "Come learn about application security & delivery!",
        title1: "Cybersecurity Talk:",
        title2: "App Security & F5 Solutions",
        date: "Thursday, 12.06.2026",
        time: "14:00-15:00",
        location: "Building 503 (CS) Room 226",
        speakerName: "Speaker Name",
        speakerRole: "Security Engineer / F5",
        theme: "f5",
        bgStyle: "curves",
        cyberOverlay: "none",
        logoVisible: true,
        logoBg: false,
        logoPosition: "top-left",
        logoSize: 95,
        avatarZoom: 440,
        avatarX: -154,
        avatarY: -386,
        fzTitle: 36,
        fzCallouts: 15,
        fzDetails: 19,
        fzSpeaker: 22,
        verticalShift: 0,
        primaryColor: "#1D252D",
        secondaryColor: "#E4002B",
        textDarkColor: "#1D252D",
        textLightColor: "#ffffff",
        layoutDirection: "ltr",
        uiLanguage: "en",
        speakerImgSrc: "https://placehold.co/300x300/1D252D/E4002B?text=Speaker",
        logoImgSrc: "Biu_tzadik_nobackground.png"
    }
};

// Advanced Drag & Drop Scoping globals
let isAdvancedLayout = false;
const DRAGGABLE_IDS = [
    'poster-logo-container', 
    'container-callout-left', 
    'container-callout-right', 
    'poster-title-container', 
    'poster-details-container', 
    'poster-speaker-container'
];

let activeDraggedElement = null;
let dragStartX = 0;
let dragStartY = 0;
let dragStartLeft = 0;
let dragStartTop = 0;

let activeResizedElement = null;
let resizeStartWidth = 0;
let resizeStartHeight = 0;
let resizeStartX = 0;
let resizeStartY = 0;
